"""Scout V2: review-only lead qualification and personalized draft generation.

Reads prospects.csv generated by scout_prospect.py. Does not send email.
Uses conservative HTTP checks, not a comprehensive accessibility/SEO audit.
"""
import csv
import datetime as dt
import html
import ipaddress
import pathlib
import re
import socket\nimport json
import urllib.error
import urllib.parse
import urllib.request
from html.parser import HTMLParser

ROOT = pathlib.Path(__file__).resolve().parent
SOURCE = ROOT / "prospects.csv"
QUEUE = ROOT / "qualified_leads.csv"
DRAFTS = ROOT / "outreach_drafts.md"
REPORT = ROOT / "qualification_report.md"

class PageParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.title = ""
        self.in_title = False
        self.viewport = False
        self.description = False
        self.form = False
        self.h1 = False
        self.contact = False\n        self.images_missing_alt = 0\n        self.images_seen = 0
    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "title": self.in_title = True
        if tag == "meta":
            if a.get("name", "").lower() == "viewport": self.viewport = True
            if a.get("name", "").lower() == "description": self.description = bool(a.get("content", "").strip())
        if tag == "form": self.form = True\n        if tag == "img":\n            self.images_seen += 1\n            if "alt" not in a: self.images_missing_alt += 1
        if tag == "h1": self.h1 = True
        if tag == "a" and any(x in (a.get("href", "") + " " + a.get("aria-label", "")).lower() for x in ("contact", "tel:", "mailto:", "quote", "estimate")):
            self.contact = True
    def handle_endtag(self, tag):
        if tag == "title": self.in_title = False
    def handle_data(self, data):
        if self.in_title: self.title += data

class NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None

def safe_host(url):
    p = urllib.parse.urlparse(url)
    if p.scheme not in ("http", "https") or not p.hostname or p.username or p.password or p.port not in (None, 80, 443):
        return None
    host = p.hostname.lower()
    if host in ("localhost",) or host.endswith((".local", ".internal")):
        return None
    try:
        ips = socket.getaddrinfo(host, None, type=socket.SOCK_STREAM)
        if not ips or not all(ipaddress.ip_address(entry[4][0]).is_global for entry in ips):
            return None
    except (socket.gaierror, ValueError):
        return None
    return host

def inspect(url):
    host = safe_host(url)
    if not host:
        return "SKIPPED_UNSAFE_OR_UNRESOLVED", None, "URL could not be safely resolved"
    # Only fetch the website origin. Do not crawl pages or collect contact details.
    origin = "https://" + host + "/"
    req = urllib.request.Request(origin, headers={"User-Agent": "ScoutBusinessResearch/1.0 (public-site review)", "Accept": "text/html"})
    try:
        with urllib.request.build_opener(NoRedirect).open(req, timeout=9) as res:
            kind = res.headers.get("Content-Type", "").lower()
            if "text/html" not in kind: return "NOT_HTML", None, "Homepage did not return HTML"
            raw = res.read(250_000)
            parser = PageParser()
            parser.feed(raw.decode("utf-8", errors="replace"))
            parser.response_headers = dict(res.headers.items())\n            return "FETCHED", parser, "Public homepage HTML inspected"
    except urllib.error.HTTPError as e:
        return "HTTP_" + str(e.code), None, "Homepage fetch did not return HTML; no defect inferred"
    except Exception as e:
        return "UNAVAILABLE", None, "Fetch failed (" + type(e).__name__ + "); no defect inferred"

def choose_offer(parser):
    if not parser: return "Website review", "No website problem verified", 0
    # Findings describe observable responses, not confirmed security vulnerabilities.
    signals = []
    if not parser.viewport: signals.append("Homepage HTML lacks a viewport meta tag")
    if not parser.description: signals.append("Homepage HTML lacks a meta description")
    if not parser.h1: signals.append("Homepage HTML lacks an H1 heading")
    if parser.images_missing_alt:
        signals.append(str(parser.images_missing_alt)+" of "+str(parser.images_seen)+" homepage images lack alt attributes")
    headers = {k.lower():v for k,v in getattr(parser,"response_headers",{}).items()}
    if "content-security-policy" not in headers:
        signals.append("Homepage HTTP response lacks a Content-Security-Policy header (configuration review suggested)")
    if "x-content-type-options" not in headers:
        signals.append("Homepage HTTP response lacks an X-Content-Type-Options header")
    if not signals: return "Website review", "No targeted gaps observed in fetched homepage", 0
    return "Website accessibility, metadata and security-header review", "; ".join(signals), min(60, 20+8*len(signals))

def draft(row):
    business = row["business"].strip() or row["domain"]
    offer = row["recommended_service"]
    evidence = row["observed_signal"]
    if row["inspection_status"] == "FETCHED" and row["priority_score"] >= 25:
        note = "In a preliminary review of your public homepage HTML, I noticed: " + evidence + ". This may be intentional or handled elsewhere on your site, so I would confirm before recommending changes."
    else:
        note = "I came across your business while researching local service companies. I haven't verified any website problems, so I wouldn't want to assume changes are needed."
    return ("Subject: Quick question about " + business + "'s website\n\n"
            + "Hello,\n\n" + note + "\n\n"
            + "Cairnflow Private helps businesses with practical website improvements, including " + offer.lower() + ". "
            + "Would a short, no-obligation website review be useful?\n\n"
            + "Best,\nCairnflow Private\n"
            + "[Add approved sender identity, contact information and opt-out wording before any outreach]\n")

def main():
    if not SOURCE.exists(): raise SystemExit("Missing operations/prospects.csv; run scout_prospect.py first")
    with SOURCE.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    seen = set()
    results = []
    for row in rows:
        host = row.get("domain", "").lower()
        if not host or host in seen: continue
        seen.add(host)
        status, parser, inspection_note = inspect(row.get("website", ""))
        offer, signal, score = choose_offer(parser)
        if status != "FETCHED": score = 0
        # Prioritize actionable observations, not the age or reputation of a business.
        result = dict(row)
        result.update(inspection_status=status, inspection_note=inspection_note,
                      observed_signal=signal, recommended_service=offer,
                      priority_score=score, outreach_status="DRAFT_ONLY",
                      review_status="HUMAN_REVIEW_REQUIRED")
        results.append(result)
    results.sort(key=lambda r: (-int(r["priority_score"]), r["domain"]))
    columns = list(dict.fromkeys([*(rows[0].keys() if rows else []), "inspection_status",
        "inspection_note", "observed_signal", "recommended_service", "priority_score",
        "outreach_status", "review_status"]))
    with QUEUE.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=columns, extrasaction="ignore")
        w.writeheader()
        w.writerows(results)
    top = results[:10]
    lines = ["# Scout outreach drafts — NOT SENT", "",
             "All candidates require human validation of business identity, issue, relevance, legal outreach compliance and email address before sending.", ""]
    for i, row in enumerate(top, 1):
        lines.extend([f"## {i}. {row['business']} — {row['domain']}",
                      f"Website: {row['website']}",
                      f"Score: {row['priority_score']} / 60 | Inspection: {row['inspection_status']}",
                      f"Preliminary observation: {row['observed_signal']}", "",
                      draft(row), "---", ""])
    DRAFTS.write_text("\n".join(lines), encoding="utf-8")
    REPORT.write_text("\n".join([
        "# Scout qualification report", "",
        "Generated: " + dt.datetime.now(dt.timezone.utc).isoformat(),
        f"Candidates: {len(results)}",
        f"Homepages inspected: {sum(x['inspection_status'] == 'FETCHED' for x in results)}",
        f"Preliminary metadata candidates: {sum(int(x['priority_score']) >= 25 for x in results)}",
        f"Drafts prepared: {len(top)}",
        "Emails sent: 0",
        "",
        "Findings are verified observations from the fetched HTML/HTTP response, not proof of defects or exploitable vulnerabilities. Browser and human review required.",\n        "Passive GET-only inspection: no exploitation, scanning, login attempts, or penetration testing.",
        "No contacts were harvested and no email was sent."
    ]) + "\n", encoding="utf-8")
    print(f"Scout qualified {len(results)} candidates, inspected {sum(x['inspection_status']=='FETCHED' for x in results)} pages, prepared {len(top)} unsent drafts")

if __name__ == "__main__":
    main()
